/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at
a random position.
Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

*/

import java.util.*;
class findTheDifference{
    public static void main(String[]args){
        Scanner sn=new Scanner(System.in);
        String s=sn.nextLine();
        String t=sn.nextLine();

        int sum=0;

        for(char ch:t.toCharArray()){
            sum+=ch;
        }
        for(char ch:s.toCharArray()){
            sum-=ch;
        }
        System.out.println((char)sum);
    }
}